sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alex_t/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alex_t/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "simple-react-app"
  env: "Simplereactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-711190079749"
  bucket_path: "simple-react-app"

  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
